version: '2'
services:

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: endurance_user
      POSTGRES_PASSWORD: sdejeladeboiteen69
      POSTGRES_DB: endurance
    ports:
      - 5432:5432

